### ISSUE TITLE
LINEA DEL TIEMPO SOBRE LA WEB 1.0, 2.0 , 3.0

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-7-Jaczibeth#1]
Linea de tiempo sobre la web 1.0,2.0,3.0.
Jaczibeth Cruz Ramírez 
1BS
[_línea de tiempo sobre la web 1.0 , 2.0 , 3.0_Jaczibeth_1bs .pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Jaczibeth/files/9793318/_linea.de.tiempo.sobre.la.web.1.0.2.0.3.0_Jaczibeth_1bs.pdf)

**Comment by 11042002** [comment]
Tu calificación es de: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
